// <auto-generated />
using System;
using Job_Search.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Job_Search.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231025164932_JobSearch")]
    partial class JobSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Job_Search.Jobs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Beginning")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfDismissal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrganisationID")
                        .HasColumnType("integer");

                    b.Property<string>("OrganisationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.Property<int>("PositionID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Job_Search.Openings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("OrganisationID")
                        .HasColumnType("integer");

                    b.Property<string>("OrganisationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PositionID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Openings");
                });
#pragma warning restore 612, 618
        }
    }
}
